//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artical_Task.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Comment = new HashSet<Comment>();
        }

        public int id { get; set; }
        [Required(ErrorMessage = "Please enter your username...")]
        public string username { get; set; }
        [Required(ErrorMessage = "Please enter your password...")]
        [MinLength(8, ErrorMessage = "Password must be more than 8 letters...")]
        public string password { get; set; }
        [MinLength(11, ErrorMessage = "mobile number must be 11 numbers...")]
        [MaxLength(11, ErrorMessage = "mobile number must be 11 numbers...")]
        public string mobile { get; set; }
        public Nullable<int> job_title { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
    }
}
